### ISSUE TITLE
Scale Wrong

### ISSUE THREAD

**Issue by Fathomk** [shaanaliyev/r-place-overlay#3]
The Scaling is wrong, do you know if this is a problem with the image I inserted or do I have to put more code in the rentry script to fix it?

**Comment by sh2aliyev** [comment]
The scaling is wrong because the main script takes 0 (zero) as the base point for `x` and `y`. For example, currently, the r/place canvas starts from `x:-1000, y:-1000`, but you should think of it as starting from 0 and 0. After that, you can move the image to the right by adding to `x` and down by adding to `y`, and so on.

Feel free to comment whether you fix it or not.

> Note: The image you are using when creating the template should be pixel-perfect sized with the canvas. This means, for example, you cannot use a 1600x1200 image to fit a 25x10 space.
